# Floating windows
windowrule = float on, match:tag floating-window
windowrule = center on, match:tag floating-window
windowrule = size 875 600, match:tag floating-window

windowrule = tag +floating-window, match:class (clipse|Bluetui|Impala|Wiremix|btop)

