# Blur
layerrule {
    name = blur
    blur = on
    blur_popups = on
    ignore_alpha = 0
    match:namespace = (waybar|walker|swaync-control-center)
}


# Floating windows
windowrule = tag +floating-window, match:class (clipse|Bluetui|Impala|Wiremix|btop)

windowrule {
    name = floating_windows
    float = on
    center = on
    size = 875 600
    match:tag = floating-window
}

# Ignore maximize requests from apps
windowrule = suppress_event maximize, match:class .*

# Fix some dragging issues with XWayland
windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0

xwayland {
	force_zero_scaling = true
}


